### ISSUE TITLE
Use attachment ID instead of URL

### ISSUE THREAD

**Issue by caesar** [junaidbhura/wp-image#2]
Great plugin! I started the ticket you just shared it to, years ago, but sadly I gradually had less and less time for working on WordPress and I never got around to doing anything similar myself; I've just been living with WordPress' clumsy and broken image support.

One thing I would suggest, is to use the attachment ID of the image instead of the URL in the shortcode. One of the big points of having a shortcode instead of a plain `<img>` tag is to be able to update the URLs automatically when the site URL changes. If the URL is hardcoded this is harder.

**Comment by caesar** [comment]
Sorry, on a closer look I see you do actually use the ID as well as the URL. I'm not sure what the point is of having both, though?

**Comment by junaidbhura** [comment]
Hey @caesar great to meet you! I totally agree with you about the clumsiness of the current approach. I've brought this up on the #core Slack channel, to mixed reviews. Looks like people want to focus their efforts on Gutenberg.

To answer your question, there are two reasons why I've added the URL:

1. There's less processing when adding the image in the editor
1. In case someone wants to use the URL in the shortcode to process quickly without hitting the database again

Again, this is just a prototype. So it's all still open to change! :)

**Comment by caesar** [comment]
Okay, I see where you're coming from. Personally though I still feel it would be better to generate the URL on the fly, despite the extra database hits, because hard-coding it seems to defeat one of the main purposes of having a shortcode instead of a hard-coded `img` tag…
